#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "vlcraptor"

command = ARGV.shift

case command
when "autoplay"
  Vlcraptor.autoplay(ARGV.shift)
when "crossfade"
  Vlcraptor.crossfade(ARGV.shift)
when "play"
  Vlcraptor.player
when "skip"
  Vlcraptor.skip
when "scrobble"
  Vlcraptor.scrobble(ARGV.shift)
else
  puts "unknown command #{command}"
end
