#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "vlcraptor"

command = ARGV.shift

case command
when "skip"
  Vlcraptor.skip
when "play"
  Vlcraptor.player
else
  puts "unknown command #{command}"
end
