#!/usr/bin/env ruby

# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")

require "vlcraptor"

command = ARGV.shift

case command
when "autoplay"
  Vlcraptor.autoplay(ARGV.shift)
when "crossfade"
  Vlcraptor.crossfade(ARGV.shift)
when "list"
  Vlcraptor.list
when "pause"
  Vlcraptor.pause
when "play"
  Vlcraptor.play
when "player"
  Vlcraptor.player
when "queue"
  Vlcraptor.queue(ARGV)
when "scrobble"
  Vlcraptor.scrobble(ARGV.shift)
when "skip"
  Vlcraptor.skip
when "stop"
  Vlcraptor.stop
else
  puts "Unknown command \"#{command}\":"
  puts "  autoplay on/off: continue playing tracks or stop at the end of current track"
  puts "  crossfade on/off: 5 second crossfade when changing tracks"
  puts "  list: list current queue"
  puts "  pause: pause current track (resume with play)"
  puts "  play: resume after pause/stop"
  puts "  player: start the player"
  puts "  queue paths: queue folders or files containing music tracks"
  puts "  scrobble on/off: send track information to last.fm (requires an api key)"
  puts "  skip: skip the current track"
  puts "  stop: stop the player (resume with play)"
end
